#conda env export --no-builds | findstr -v "prefix" > environment.yml
#conda env create --file=environment.yml
name: yolo7
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - freetype=2.10.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lerc=3.0
  - libdeflate=1.8
  - libpng=1.6.37
  - libtiff=4.4.0
  - libuv=1.40.0
  - libwebp=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy-base=1.23.1
  - openssl=1.1.1q
  - pip=22.2.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.13
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - requests=2.28.1
  - six=1.16.0
  - sqlite=3.39.3
  - tk=8.6.12
  - torchaudio=0.12.1
  - typing_extensions=4.3.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - asttokens==2.0.8
    - backcall==0.2.0
    - colorama==0.4.5
    - contourpy==1.0.5
    - cycler==0.11.0
    - decorator==5.1.1
    - executing==1.1.0
    - fonttools==4.37.4
    - google-auth==2.12.0
    - idna==3.4
    - ipython==8.5.0
    - jedi==0.18.1
    - kiwisolver==1.4.4
    - matplotlib==3.6.0
    - matplotlib-inline==0.1.6
    - numpy==1.23.3
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==1.5.0
    - parso==0.8.3
    - pickleshare==0.7.5
    - pillow==9.2.0
    - prompt-toolkit==3.0.31
    - psutil==5.9.2
    - pure-eval==0.2.2
    - pygments==2.13.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.2.1
    - pyyaml==6.0
    - scipy==1.9.1
    - seaborn==0.12.0
    - setuptools==59.5.0
    - stack-data==0.5.1
    - thop==0.1.1-2209072238
    - torch==1.12.1
    - torchvision==0.13.1
    - tqdm==4.64.1
    - traitlets==5.4.0
    - urllib3==1.26.12
    - wcwidth==0.2.5
